### ISSUE TITLE
Scaffold ordering, and meta on merges?

### ISSUE THREAD

**Issue by ckeeling** [bcgsc/RAILS#18]
Hi Rene,

Two quick clarifications needed. LINKS reorders/renames the scaffold IDs based on length. I'm using RAILS after LINKS.  If RAILS merges two scaffolds, does it keep one of these IDs, or does it reorder/rename them too for the final scaffolds?  Also, is there a file that describes which scaffolds are merged with RAILS? Is it *scaffolds_GAPseqList.txt? What is the format of this output?
Thanks!
Chris

**Comment by warrenlr** [comment]
Hi Chris,

RAILS does rename them: its by design to help manage sequences better (since names can be long). There is no correspondance file, although sequences are numbered (increasing) as they are read:    

>tigFoo  (this will be 1)
...
>tigBar (this will be 2)
...


The scaffold fasta output captures the scaffolding steps:

```
scaffold1,7484,f127Z7068k12a0.58m42_f3090z62k7a0.14m76_f1473z354

contig chain representing the layout:

e.g. f127Z7068k12a0.58m42_f3090z62k7a0.14m76_f1473z354

means: contig f127 (strand=f/+), size (z) 7068 (Z if contig was used as the seed sequence) has 12 links (k), link ratio of 0.58 (a) with a mean gap of 42nt (m) with reverse (r) of contig 3090 (size 62) on the right. if m values are negative, it's just that a possible overlap was calculated using the mean distance supplied by the user and the position of the reads flanking the contig. Negative m values imply that there's a possible overlap between the contigs. But since the pairing distance distribution usually follows a Normal/Gaussian distribution, some distances are expected to be larger than the median size expected/observed. In reality, if the exact size was known between each paired-reads, we wouldn't expect much negative m values unless a break occurred during the contig extension (likely due to base errors/SNPs).
```

The *scaffolds_GAPseqList.txt lists the [long] read names from the supplied -q input having contributed sequences to the gaps, in the same order as the filled-gap listed in the contig chain.  I believe this file was originally created for testing purposes.

I suggest looking at the SARS example in the distribution.

Best,
Rene
