### ISSUE TITLE
No script for assembly

### ISSUE THREAD

**Issue by bioramg** [bcgsc/RAILS#21]
Hi,
I am having plant mitochondrial contigs from SPAdes assembly using Illumina reads. I would like to make a scaffold and gap filling with ONT reads.  How to convert ONT reads (.fastq) into fof format and what are the necessary commands to execute both cobbler and Rails? 
Please help me in this regard.

**Comment by warrenlr** [comment]
Thank you for your message and interest in cobbler/RAILS.

My first suggestion is to consult the README, and try the demo packaged with the tools. This will confirm proper install of the tools.  The demo/test will also be informative on how to run these tools in a pipeline, with the supplied bash script.

for 1) fastq to fasta conversion is an easy scripting exercise. However, there are tools to facilitate the task like _seqtk_
```
> seqtk seq -A input.fq output.fa

Usage:   seqtk seq [options] <in.fq>|<in.fa>
```

for 2) The title of your issue is inaccurate, as we do provide three scripts for assembly (in the _./bin_ folder)

For nanopore reads, you can run either _runRAILSminimap.sh_  or _runRAILSminimapSTREAM.sh_
The latter will be faster as no intermediate bam files are created, the alignments are streamed directly in cobbler, then RAILS. Still, I recommend you run the former first to familiarize yourself with the process.

For both, ensure that you create symbolic links to cobbler and RAILS in your run directory and that minimap2 and  samtools are both in your PATH.

good luck!

**Comment by bioramg** [comment]
Thank you.
